import { assertRcv018TextHash, canonicalizeRcv018 } from "./rcv018Canonical";
import { validateLowercaseUuidV1, validateSha256HexV1, validateVersionV1 } from "../contracts/rcv018EvidenceContradictionContractV1";
import { buildRcv018Analysis } from "./rcv018AnalysisBuilder";
import type { Rcv018ReadBundle } from "./rcv018PostgresReadRepository";

export type Rcv018ReadVerificationCode = "ANALYSIS_NOT_FOUND" | "MISSING_DATA" | "MALFORMED_DATA" | "INCONSISTENT_DATA" | "HISTORICALLY_UNVERIFIABLE" | "VERSION_MISMATCH" | "HASH_MISMATCH" | "CANONICAL_MISMATCH" | "C1_IDENTITY_MISMATCH" | "MEMBERSHIP_MISMATCH" | "DUPLICATE_MEMBERSHIP" | "ORDERING_VIOLATION" | "PAIR_COMPLETENESS_MISMATCH" | "FINDING_SET_MISMATCH" | "UNSUPPORTED_STATE";
export class Rcv018ReadVerificationError extends Error { constructor(public readonly code: Rcv018ReadVerificationCode, public readonly path: string, message: string) { super(`${path}: ${message}`); this.name = "Rcv018ReadVerificationError"; } }
export interface Rcv018VerifiedRead { readonly bundle: Rcv018ReadBundle; readonly analysisId: string; readonly analysisHash: string; readonly assertionCount: number; readonly pairCount: number; readonly findingHashes: readonly string[]; }
const fail = (code: Rcv018ReadVerificationCode, path: string, message: string): never => { throw new Rcv018ReadVerificationError(code, path, message); };
const arr = (v: unknown, p: string): readonly Record<string, unknown>[] => Array.isArray(v) ? v as readonly Record<string, unknown>[] : fail("MALFORMED_DATA", p, "expected rows");
function ordinals(rows: readonly Record<string, unknown>[], path: string): void { const seen = new Set<string>(); rows.forEach((r, i) => { if (typeof r.ordinal !== "string" && typeof r.ordinal !== "number") fail("MALFORMED_DATA", `${path}[${i}]`, "missing ordinal"); const o = String(r.ordinal); if (seen.has(o)) fail("DUPLICATE_MEMBERSHIP", path, "duplicate ordinal"); seen.add(o); if (Number(o) !== i) fail("ORDERING_VIOLATION", path, "non-contiguous ordinal"); }); }
function hashRow(row: Record<string, unknown>, path: string): void { const h = row.hash ?? row.analysis_hash ?? row.assertion_hash ?? row.value_domain_hash ?? row.comparison_domain_hash ?? row.finding_hash; if (h !== undefined) { try { validateSha256HexV1(h, path); } catch { fail("HASH_MISMATCH", path, "invalid hash"); } } }
const s = (v: unknown): string => String(v);
function reconstructInput(bundle: Rcv018ReadBundle): any {
  const domains = arr(bundle.valueDomains, "valueDomains").map((d) => ({ value: { valueDomainId: d.value_domain_id, valueDomainVersion: Number(d.value_domain_version), kind: d.kind, allowedValues: arr(bundle.valueDomainValues, "valueDomainValues").filter((v) => s(v.value_domain_id) === s(d.value_domain_id) && s(v.value_domain_version) === s(d.value_domain_version)).sort((a,b)=>Number(a.ordinal)-Number(b.ordinal)).map((v)=>v.value) }, canonical: d.canonical, hash: d.value_domain_hash }));
  const comparisons = arr(bundle.comparisonDomains, "comparisonDomains").map((d) => ({ value: { comparisonDomainId:d.comparison_domain_id, comparisonDomainVersion:Number(d.comparison_domain_version), propertyId:d.property_id, valueDomainId:d.value_domain_id, valueDomainVersion:Number(d.value_domain_version), valueDomainHash:d.value_domain_hash, comparisonKeySchema:arr(bundle.comparisonKeys,"comparisonKeys").filter((k)=>s(k.comparison_domain_id)===s(d.comparison_domain_id)&&s(k.comparison_domain_version)===s(d.comparison_domain_version)).sort((a,b)=>Number(a.ordinal)-Number(b.ordinal)).map((k)=>({key:k.key,type:k.type})), ruleFamily:d.rule_family, incompatibilityPairs:arr(bundle.incompatibilityPairs,"incompatibilityPairs").filter((p)=>s(p.comparison_domain_id)===s(d.comparison_domain_id)&&s(p.comparison_domain_version)===s(d.comparison_domain_version)).sort((a,b)=>Number(a.ordinal)-Number(b.ordinal)).map((p)=>[p.left_value,p.right_value]) }, canonical:d.canonical, hash:d.comparison_domain_hash }));
  const assertions = arr(bundle.assertions,"assertions").map((a) => ({ value:{ assertionId:a.assertion_id, subjectId:a.subject_id, propertyId:a.property_id, comparisonDomainId:a.comparison_domain_id, comparisonDomainVersion:Number(a.comparison_domain_version), comparisonDomainHash:a.comparison_domain_hash, valueDomainId:a.value_domain_id, valueDomainVersion:Number(a.value_domain_version), valueDomainHash:a.value_domain_hash, value:a.value, comparisonContext:arr(bundle.assertionContexts,"assertionContexts").filter((r)=>s(r.assertion_id)===s(a.assertion_id)).sort((x,y)=>Number(x.ordinal)-Number(y.ordinal)).map((r)=>r.type==='UUID'?{key:r.key,type:r.type,uuidValue:r.uuid_value}:{key:r.key,type:r.type,tokenValue:r.token_value}), evidenceBasis:arr(bundle.evidenceBasis,"evidenceBasis").filter((r)=>s(r.assertion_id)===s(a.assertion_id)).sort((x,y)=>Number(x.ordinal)-Number(y.ordinal)).map((r)=>({evidenceRelationId:r.evidence_relation_id,evidenceId:r.evidence_id,artifactVersionId:r.artifact_version_id,statementKind:r.statement_kind,statementId:r.statement_id})), historicalBindings:arr(bundle.historicalBindings,"historicalBindings").filter((r)=>s(r.assertion_id)===s(a.assertion_id)).sort((x,y)=>Number(x.ordinal)-Number(y.ordinal)).map((r)=>{ if(r.kind==='CLAIM_VERSION') return {kind:r.kind,claimVersionId:r.claim_version_id}; if(r.kind==='STATEMENT') return {kind:r.kind,statementKind:r.statement_kind,statementId:r.statement_id}; if(r.kind==='ARTIFACT_VERSION') return {kind:r.kind,artifactVersionId:r.artifact_version_id}; if(r.kind==='RCV016_SNAPSHOT') return {kind:r.kind,snapshotId:r.rcv016_snapshot_id,snapshotHash:r.rcv016_snapshot_hash}; return {kind:r.kind,analysisId:r.rcv017_analysis_id,analysisHash:r.rcv017_analysis_hash}; }) }, canonical:a.canonical, hash:a.assertion_hash }));
  return { analysisId:bundle.analysis!.analysis_id, assertions, valueDomains:domains, comparisonDomains:comparisons, contractBinding:{contractId:bundle.analysis!.contract_id,contractVersion:Number(bundle.analysis!.contract_version),contractHash:bundle.analysis!.contract_hash}, algorithmBinding:{algorithmId:bundle.analysis!.algorithm_id,algorithmVersion:Number(bundle.analysis!.algorithm_version),algorithmHash:bundle.analysis!.algorithm_hash} };
}

/** Independent, read-only authentication of the raw persisted bundle. */
export function verifyRcv018ReadBundle(raw: unknown): Rcv018VerifiedRead {
  if (!raw || typeof raw !== "object") fail("MALFORMED_DATA", "bundle", "expected bundle");
  const bundle = raw as Rcv018ReadBundle;
  const analysis = bundle.analysis;
  if (!analysis) throw new Rcv018ReadVerificationError("ANALYSIS_NOT_FOUND", "analysis", "analysis was not found");
  try { validateLowercaseUuidV1(analysis.analysis_id, "analysis.analysis_id"); validateVersionV1(analysis.contract_version, "analysis.contract_version"); validateVersionV1(analysis.algorithm_version, "analysis.algorithm_version"); validateSha256HexV1(analysis.contract_hash, "analysis.contract_hash"); validateSha256HexV1(analysis.algorithm_hash, "analysis.algorithm_hash"); validateSha256HexV1(analysis.analysis_hash, "analysis.analysis_hash"); } catch (e) { fail("MALFORMED_DATA", "analysis", e instanceof Error ? e.message : "invalid analysis"); }
  try { assertRcv018TextHash(String(analysis.canonical), analysis.analysis_hash, "analysis.analysis_hash"); } catch { fail("CANONICAL_MISMATCH", "analysis", "analysis Canonical/hash mismatch"); }
  const memberships = ["analysisAssertions", "analysisValueDomains", "analysisComparisonDomains", "analysisFindings"] as const; for (const key of memberships) ordinals(arr(bundle[key], key), key);
  for (const row of [...arr(bundle.assertions, "assertions"), ...arr(bundle.valueDomains, "valueDomains"), ...arr(bundle.comparisonDomains, "comparisonDomains"), ...arr(bundle.findings, "findings")]) hashRow(row, "row");
  const assertionIds = new Set(arr(bundle.analysisAssertions, "analysisAssertions").map((r) => String(r.assertion_id))); if (assertionIds.size !== bundle.analysisAssertions.length) fail("DUPLICATE_MEMBERSHIP", "analysisAssertions", "duplicate assertion");
  const prerequisites = arr(bundle.statementPrerequisites ?? [], "statementPrerequisites");
  for (const binding of arr(bundle.historicalBindings, "historicalBindings")) {
    if (binding.kind !== "STATEMENT") continue;
    if (binding.statement_kind !== "EvidenceArtifactBinding") fail("C1_IDENTITY_MISMATCH", "historicalBindings", "unsupported statement family");
    const id = String(binding.statement_id);
    if (!prerequisites.some((row) => String(row.id) === id)) fail("C1_IDENTITY_MISMATCH", "historicalBindings", "selected EvidenceArtifactBinding prerequisite missing");
  }
  const findingHashes = arr(bundle.analysisFindings, "analysisFindings").map((r) => String(r.finding_hash)); if (new Set(findingHashes).size !== findingHashes.length) fail("DUPLICATE_MEMBERSHIP", "analysisFindings", "duplicate finding");
  const n = assertionIds.size; const pairCount = n < 2 ? 0 : n * (n - 1) / 2;
  let rebuilt: any; try { rebuilt = buildRcv018Analysis(reconstructInput(bundle)); } catch (e) { fail("INCONSISTENT_DATA", "bundle", e instanceof Error ? e.message : "persisted semantic state is inconsistent"); }
  if (rebuilt.hash !== analysis.analysis_hash || rebuilt.canonical !== analysis.canonical) fail("CANONICAL_MISMATCH", "analysis", "persisted analysis differs from independent replay");
  const expectedFindingHashes = rebuilt.analysis.contradictionFindingHashes.slice().sort();
  if (expectedFindingHashes.length !== findingHashes.length || expectedFindingHashes.some((h: string, i: number) => h !== findingHashes.slice().sort()[i])) fail("FINDING_SET_MISMATCH", "analysisFindings", "persisted finding set differs from replay");
  const assertionMemberIds = arr(bundle.analysisAssertions,"analysisAssertions").map((r)=>s(r.assertion_id)); const persistedIds = arr(bundle.assertions,"assertions").map((r)=>s(r.assertion_id));
  if (assertionMemberIds.length !== persistedIds.length || assertionMemberIds.some((id)=>!persistedIds.includes(id))) fail("MEMBERSHIP_MISMATCH", "analysisAssertions", "assertion membership does not match persisted assertions");
  return Object.freeze({ bundle, analysisId: String(analysis.analysis_id), analysisHash: String(analysis.analysis_hash), assertionCount: n, pairCount, findingHashes: Object.freeze(findingHashes) });
}
export const verifyRcv018Read = verifyRcv018ReadBundle;
