const assert=require("node:assert/strict");const test=require("node:test");
const {RCV016_BOUNDED_PAYLOAD_FIELDS_V1}=require("../dist/contracts/rcv016ProvenanceContractV1");
const {canonicalizeRcv016,sha256Rcv016Text}=require("../dist/services/rcv016Canonical");
const {validateRcv016PayloadLimits}=require("../dist/services/rcv016PayloadLimits");
const {validateAndCanonicalizeRcv016ArtifactCapture}=require("../dist/services/rcv016ArtifactCapture");
const {validateRcv016TraversalPolicy}=require("../dist/services/rcv016TraversalPolicy");
const {buildRcv016ProvenanceSnapshot}=require("../dist/services/rcv016SnapshotBuilder");
const {buildRcv017ClaimEvidenceDependencyAnalysis}=require("../dist/services/rcv017AnalysisBuilder");
const {verifyRcv017PersistedAnalysis,Rcv017ReadIntegrityError}=require("../dist/services/rcv017ReadVerifier");
const TS="2026-09-02T10:00:00.000000Z",ANALYSIS_ID=id(800),SNAPSHOT_ID=id(900),EMPTY="{}",EMPTY_HASH=sha256Rcv016Text(EMPTY);
function id(n){return `50000000-0000-0000-0000-${n.toString(16).padStart(12,"0")}`;}
function common(statementId){return{statementId,observedAt:TS,validFrom:null,validTo:null,initiator:null,rationale:null,foundation:null,supersedesStatementId:null,createdAt:TS};}
function limits(){const d={limitsId:"rcv017-read-limits",limitsVersion:"1"};for(const f of RCV016_BOUNDED_PAYLOAD_FIELDS_V1)d[f]=1_000_000;const c=canonicalizeRcv016(d);return validateRcv016PayloadLimits({...d,definitionCanonical:c.canonical,definitionHash:c.hash});}
function snapshotPolicy(){const d={policyId:"rcv017-read-snapshot",policyVersion:"1",maxRoots:20,maxNodes:100,maxEdges:100,maxDepth:10,maxCanonicalSnapshotBytes:1_000_000,allowedRelationships:["cites","derived_from","incorporates","quotes","reposts","syndicated_from","uses_information_from"],deterministicOrdering:"schema_category_then_canonical_key_lexicographic_v1",visitedSemantics:"expand_node_once_include_statement_once_diagnose_cycles_v1"};const c=canonicalizeRcv016(d);return validateRcv016TraversalPolicy({...d,definitionCanonical:c.canonical,definitionHash:c.hash});}
function artifact(n){const c=validateAndCanonicalizeRcv016ArtifactCapture({schema:{id:"factbase-artifact-version-capture",version:"1"},locator:null,mediaType:null,title:`Artifact ${n}`,publishedAt:null,observedAt:TS,retrievedAt:null,representation:{kind:"metadata_only",hashAlgorithm:null,contentHash:null}},limits());return{artifactVersionId:id(n),artifactId:id(1000+n),versionNumber:1,captureSchemaId:"factbase-artifact-version-capture",captureSchemaVersion:"1",captureCanonical:c.canonical,captureHash:c.hash,createdAt:TS};}
function snapshot(){return buildRcv016ProvenanceSnapshot({snapshotIdentity:{snapshotSchemaId:"factbase-provenance-snapshot",snapshotSchemaVersion:"1",canonicalizationId:"jcs-rfc8785",canonicalizationVersion:"1",hashAlgorithm:"sha-256"},builderIdentity:{builderId:"factbase-provenance-snapshot-builder",builderVersion:"1",builderArtifactHash:"a".repeat(64)},traversalPolicy:snapshotPolicy(),roots:[id(1),id(2),id(4)],artifactVersions:[1,2,3,4].map(artifact),sourceVersions:[],artifactProvenanceStatements:[{family:"ArtifactProvenanceStatement",...common(id(500)),subjectArtifactVersionId:id(1),relationship:"quotes",objectArtifactVersionId:id(2)},{family:"ArtifactProvenanceStatement",...common(id(501)),subjectArtifactVersionId:id(1),relationship:"quotes",objectArtifactVersionId:id(3)},{family:"ArtifactProvenanceStatement",...common(id(502)),subjectArtifactVersionId:id(2),relationship:"quotes",objectArtifactVersionId:id(3)},{family:"ArtifactProvenanceStatement",...common(id(503)),subjectArtifactVersionId:id(1),relationship:"quotes",objectArtifactVersionId:id(3)},{family:"ArtifactProvenanceStatement",...common(id(504)),subjectArtifactVersionId:id(2),relationship:"quotes",objectArtifactVersionId:id(1)}],sourceRelationshipStatements:[],artifactSourceAttributions:[],evidenceArtifactBindings:[1,2,3,4].map(n=>({family:"EvidenceArtifactBinding",...common(id(400+n)),subjectEvidenceId:id(200+n),relationship:"bound_to",objectArtifactVersionId:id(n===3?1:n)})),knowledgeStateStatements:[{family:"KnowledgeStateStatement",...common(id(601)),subjectArtifactVersionId:id(1),scope:"upstream_provenance",state:"unknown"},{family:"KnowledgeStateStatement",...common(id(602)),subjectArtifactVersionId:id(2),scope:"upstream_provenance",state:"partial"},{family:"KnowledgeStateStatement",...common(id(603)),subjectArtifactVersionId:id(3),scope:"upstream_provenance",state:"known"}]});}
function policy(){const d={schemaId:"factbase-dependency-analysis-policy",schemaVersion:"1",policyId:id(700),policyVersion:1,relationshipClassificationCatalogId:"factbase-dependency-relationship-classification",relationshipClassificationCatalogVersion:"1",enabledDependencyRelationships:["quotes"],evidenceDirectionPartitionRule:"supports_and_contradicts_separate_contextualizes_excluded",reflexiveClosureRule:"anchor_depth_zero_then_enabled_dependency_edges_minimum_distance",commonUpstreamRule:"same_exact_artifact_version_in_two_or_more_reflexive_branch_closures",negativeFindingRule:"unordered_same_direction_pair_with_disjoint_reflexive_closures",knowledgeLimitationRule:"snapshot_unknown_partial_or_derived_unrecorded_in_reached_set",witnessSelectionRule:"fewest_edges_then_ascii_statement_id_sequence",findingVocabularyRule:"rcv017_closed_four_finding_vocabulary_v1",cycleHandlingRule:"expand_once_per_branch_at_minimum_distance",deterministicOrderingRule:"rcv017_explicit_total_order_v1",maxEvidenceRelations:20,maxBindings:20,maxArtifactVersions:100,maxStatements:100,maxDependencyDepth:10,maxFindings:100,maxCanonicalBytes:1_000_000,canonicalizationId:"jcs-rfc8785",canonicalizationVersion:"1",hashAlgorithm:"sha-256"};const c=canonicalizeRcv016(d);return{definition:d,canonical:c.canonical,hash:c.hash};}
function built(){const snap=snapshot(),p=policy(),relations=[1,2,3,4].map(n=>({claimVersionEvidenceRelationId:id(100+n),evidenceId:id(200+n),direction:"supports"})),bindings=[1,2,3,4].map(n=>({claimVersionEvidenceRelationId:id(100+n),evidenceArtifactBindingStatementId:id(400+n),evidenceId:id(200+n),artifactVersionId:id(n===3?1:n)}));return{snap,result:buildRcv017ClaimEvidenceDependencyAnalysis({claimVersionId:id(10),evidenceRelations:relations,selectedBindings:bindings,provenanceSnapshot:{snapshotId:SNAPSHOT_ID,builderResult:snap},dependencyAnalysisPolicy:p,algorithmIdentity:{algorithmId:"factbase-claim-evidence-dependency-algorithm",algorithmVersion:"1",algorithmArtifactHash:"b".repeat(64)}})};}
function rawSnapshot(snap){const l=limits(),record=value=>({value,payloadLimits:l,foundationCanonical:null,foundationHash:null});return{header:{snapshotId:SNAPSHOT_ID,snapshotCanonical:snap.canonical,snapshotHash:snap.hash,persistenceCreatedAt:TS},relationalMembershipKeys:[...snap.snapshot.membershipKeys].reverse(),artifactVersions:snap.snapshot.artifactVersions.map(record),sourceVersions:[],artifactProvenanceStatements:snap.snapshot.artifactProvenanceStatements.map(record),sourceRelationshipStatements:[],artifactSourceAttributions:[],evidenceArtifactBindings:snap.snapshot.evidenceArtifactBindings.map(record),knowledgeStateStatements:snap.snapshot.knowledgeStateStatements.map(record),traversalPolicy:snapshotPolicy(),foundationTargets:{evidenceIds:[],artifactVersionIds:[],provenanceSnapshotIds:[]}};}
function bundle(){const {snap,result}=built(),p=result.projection;return{header:{analysisId:ANALYSIS_ID,...p.analysisHeader,createdAt:TS},policyHeader:p.policyHeader,policyRelationships:p.policyRelationships,evidenceRelations:p.evidenceRelations,bindings:p.bindings,sharedArtifactFindings:p.sharedArtifactFindings,sharedArtifactMembers:p.sharedArtifactMembers,commonUpstreamFindings:p.commonUpstreamFindings,commonUpstreamMembers:p.commonUpstreamMembers,commonUpstreamWitnessSteps:p.commonUpstreamWitnessSteps,noCommonUpstreamFindings:p.noCommonUpstreamFindings,knowledgeIncompleteFindings:p.knowledgeIncompleteFindings,knowledgeAffectedArtifacts:p.knowledgeAffectedArtifacts,knowledgeStateEvidence:p.knowledgeStateEvidence,derivedUnrecordedEvidence:p.derivedUnrecordedEvidence,historicalClaimVersion:{id:id(10)},historicalEvidenceRelations:p.evidenceRelations.map(r=>({...r,claimVersionId:id(10)})),historicalEvidenceIds:[id(201),id(202),id(203),id(204)],rcv016SnapshotRead:rawSnapshot(snap)};}
function clone(v){return structuredClone(v);}function recanonicalize(b,mutate){const value=JSON.parse(b.header.analysisCanonical);mutate(value);b.header.analysisCanonical=canonicalizeRcv016(value).canonical;b.header.analysisHash=sha256Rcv016Text(b.header.analysisCanonical);return b;}
function corruptSnapshotOrdering(b){const value=JSON.parse(b.rcv016SnapshotRead.header.snapshotCanonical);value.artifactProvenanceStatements.reverse();b.rcv016SnapshotRead.header.snapshotCanonical=canonicalizeRcv016(value).canonical;b.rcv016SnapshotRead.header.snapshotHash=sha256Rcv016Text(b.rcv016SnapshotRead.header.snapshotCanonical);return b;}
async function fails(mutator,code){const b=clone(bundle());mutator(b);await assert.rejects(()=>verifyRcv017PersistedAnalysis(b,"b".repeat(64)),e=>e instanceof Rcv017ReadIntegrityError&&(!code||e.code===code));}

test("valid persisted analysis verifies independently and row order is irrelevant",async()=>{const b=bundle(),before=JSON.stringify(b),verified=await verifyRcv017PersistedAnalysis(b,"b".repeat(64));assert.deepEqual(verified,{verified:true,analysisId:ANALYSIS_ID,analysisHash:b.header.analysisHash,analysisSchemaId:"factbase-claim-evidence-dependency-analysis",analysisSchemaVersion:"1"});const snapshotStatements=JSON.parse(b.rcv016SnapshotRead.header.snapshotCanonical).artifactProvenanceStatements;assert.deepEqual(snapshotStatements.map(s=>s.statementId),[id(500),id(501),id(503),id(504),id(502)]);const permuted=clone(b);for(const name of ["evidenceRelations","bindings","sharedArtifactMembers","commonUpstreamMembers","commonUpstreamWitnessSteps","knowledgeAffectedArtifacts","knowledgeStateEvidence"])permuted[name].reverse();assert.equal((await verifyRcv017PersistedAnalysis(permuted,"b".repeat(64))).verified,true);assert.equal(JSON.stringify(b),before);await assert.rejects(()=>verifyRcv017PersistedAnalysis(b,"c".repeat(64)),e=>e.code==="unsupported_schema");});

test("corrupted RCV-016 tuple ordering is rejected through the bound Snapshot verifier",async()=>{await fails(corruptSnapshotOrdering,"snapshot_integrity_mismatch");});
test("hash, JCS, and closed schema fail before semantic reproduction",async()=>{await fails(b=>b.header.analysisHash="c".repeat(64),"canonical_hash_mismatch");await fails(b=>{const value=JSON.parse(b.header.analysisCanonical);b.header.analysisCanonical=JSON.stringify(value,null,2);b.header.analysisHash=sha256Rcv016Text(b.header.analysisCanonical);},"canonical_not_jcs");await fails(b=>recanonicalize(b,a=>a.extra=true),"unsupported_schema");await fails(b=>recanonicalize(b,a=>delete a.findings),"unsupported_schema");await fails(b=>recanonicalize(b,a=>a.schemaVersion="2"),"unsupported_schema");await fails(b=>recanonicalize(b,a=>a.claimVersionId=a.claimVersionId.toUpperCase()),"unsupported_schema");});
test("Policy and exact Snapshot are independently verified",async()=>{await fails(b=>b.policyHeader.definitionHash="c".repeat(64),"policy_integrity_mismatch");await fails(b=>b.policyRelationships.push({...b.policyRelationships[0],relationship:"reposts"}),"policy_integrity_mismatch");await fails(b=>b.policyRelationships.pop(),"policy_integrity_mismatch");await fails(b=>b.rcv016SnapshotRead=null,"snapshot_integrity_mismatch");await fails(b=>b.rcv016SnapshotRead.header.snapshotHash="c".repeat(64),"snapshot_integrity_mismatch");await fails(b=>b.header.provenanceSnapshotHash="c".repeat(64),"snapshot_integrity_mismatch");});
test("historical inputs and every relational family must match Canonical",async()=>{await fails(b=>b.historicalClaimVersion=null,"historical_input_mismatch");await fails(b=>b.historicalEvidenceRelations.pop(),"historical_input_mismatch");await fails(b=>b.historicalEvidenceRelations[0].evidenceId=id(999),"historical_input_mismatch");for(const name of ["evidenceRelations","bindings","sharedArtifactFindings","sharedArtifactMembers","commonUpstreamFindings","commonUpstreamMembers","commonUpstreamWitnessSteps","noCommonUpstreamFindings","knowledgeIncompleteFindings","knowledgeAffectedArtifacts","knowledgeStateEvidence","derivedUnrecordedEvidence"])await fails(b=>b[name].pop());});
test("findings, witnesses, negatives, and knowledge are rederived rather than trusted",async()=>{await fails(b=>recanonicalize(b,a=>a.findings.pop()),"finding_reproduction_mismatch");await fails(b=>recanonicalize(b,a=>a.findings.push({...a.findings[0],artifactVersionId:id(999)})),"finding_reproduction_mismatch");await fails(b=>recanonicalize(b,a=>{const f=a.findings.find(x=>x.type==="RECORDED_COMMON_UPSTREAM");const m=f.members.find(x=>x.witness.artifactProvenanceStatementIds.length>0);m.witness.artifactVersionIds=[...m.witness.artifactVersionIds].reverse();}),"finding_reproduction_mismatch");await fails(b=>recanonicalize(b,a=>{const f=a.findings.find(x=>x.type==="NO_RECORDED_COMMON_UPSTREAM_WITHIN_SCOPE");f.lowerBranchKey=f.upperBranchKey;}),"finding_reproduction_mismatch");await fails(b=>recanonicalize(b,a=>{const f=a.findings.find(x=>x.type==="DEPENDENCY_KNOWLEDGE_INCOMPLETE");f.knowledgeStateStatementIds=[];}),"finding_reproduction_mismatch");});
test("valid alternative witnesses cannot replace the shortest lexical simple witness",async()=>{const change=(artifacts,statements)=>b=>recanonicalize(b,a=>{const f=a.findings.find(x=>x.type==="RECORDED_COMMON_UPSTREAM"&&x.upstreamArtifactVersionId===id(3));const m=f.members.find(x=>x.branchKey.evidenceArtifactBindingStatementId===id(401));m.witness={artifactVersionIds:artifacts,artifactProvenanceStatementIds:statements};});await fails(change([id(1),id(2),id(3)],[id(500),id(502)]),"finding_reproduction_mismatch");await fails(change([id(1),id(3)],[id(503)]),"finding_reproduction_mismatch");await fails(change([id(1),id(2),id(1),id(3)],[id(500),id(504),id(501)]),"finding_reproduction_mismatch");});
test("derived-unrecorded full parity and limits fail closed without repair",async()=>{await fails(b=>b.derivedUnrecordedEvidence.push({...b.derivedUnrecordedEvidence[0],artifactVersionId:id(3)}));await fails(b=>recanonicalize(b,a=>a.findings.find(x=>x.type==="DEPENDENCY_KNOWLEDGE_INCOMPLETE"&&x.derivedUnrecordedArtifactVersionIds.length).derivedUnrecordedArtifactVersionIds=[]),"finding_reproduction_mismatch");await fails(b=>{const p=JSON.parse(b.policyHeader.definitionCanonical);p.maxFindings=1;b.policyHeader.definitionCanonical=canonicalizeRcv016(p).canonical;b.policyHeader.definitionHash=sha256Rcv016Text(b.policyHeader.definitionCanonical);b.policyHeader.maxFindings=1;b.header.dependencyAnalysisPolicyHash=b.policyHeader.definitionHash;},"policy_integrity_mismatch");});
test("verifier exposes neutral technical diagnostics and no repair/current/score API",()=>{const api=require("../dist/services/rcv017ReadVerifier");assert.deepEqual(Object.keys(api).sort(),["Rcv017ReadIntegrityError","verifyRcv017PersistedAnalysis"]);for(const word of ["independent","score","current","latest","winner","repair"])assert.equal(Object.keys(api).some(k=>k.toLowerCase().includes(word)),false);});
