const assert=require("node:assert/strict");const fs=require("node:fs");const test=require("node:test");
const {Rcv017PostgresAnalysisReadRepository,Rcv017ReadRepositoryError}=require("../dist/services/rcv017PostgresReadRepository");
const ID="6abcdef0-0000-0000-0000-000000000001";
function pool(handler){const trace=[],client={async query(sql,values){trace.push({sql,values});return handler(sql,values);},release(){trace.push({sql:"RELEASE"});}};return{trace,connects:0,async connect(){this.connects++;return client;}};}
test("read repository requires an exact lowercase analysisId before connecting",async()=>{for(const value of ["bad",ID.toUpperCase(),`${ID} `]){const p=pool(()=>{throw Error("unexpected")});await assert.rejects(()=>new Rcv017PostgresAnalysisReadRepository(p).loadAnalysisById(value),Rcv017ReadRepositoryError);assert.equal(p.connects,0);}});
test("missing exact analysis returns null in one read-only repeatable-read transaction",async()=>{const p=pool(sql=>sql.startsWith("BEGIN")||sql==="COMMIT"?{rows:[],rowCount:null}:{rows:[],rowCount:0}),repo=new Rcv017PostgresAnalysisReadRepository(p);assert.equal(await repo.loadAnalysisById(ID),null);assert.deepEqual(p.trace.map(x=>x.sql),["BEGIN ISOLATION LEVEL REPEATABLE READ READ ONLY",p.trace[1].sql,"COMMIT","RELEASE"]);assert.match(p.trace[1].sql,/WHERE analysis_id=\$1/);assert.deepEqual(p.trace[1].values,[ID]);});
test("query failure rolls back and never repairs or retries",async()=>{const p=pool(sql=>{if(sql.startsWith("BEGIN"))return{rows:[]};if(sql==="ROLLBACK")return{rows:[]};throw Error("query failed")});await assert.rejects(()=>new Rcv017PostgresAnalysisReadRepository(p).loadAnalysisById(ID),/query failed/);assert.equal(p.connects,1);assert.equal(p.trace.filter(x=>x.sql==="ROLLBACK").length,1);});
test("read repository source is retrieval-only and preserves raw Canonical TEXT",()=>{const source=fs.readFileSync("src/services/rcv017PostgresReadRepository.ts","utf8");assert.doesNotMatch(source,/\b(?:INSERT|UPDATE|DELETE|ALTER|CREATE|DROP)\b|JSON\.(?:parse|stringify)|WITH\s+RECURSIVE|ORDER\s+BY\s+created_at\s+DESC|latest|current|winner|effective|best|evidence_assessment|source_relationship/i);assert.match(source,/analysis_canonical AS "analysisCanonical"/);assert.match(source,/WHERE analysis_id=\$1/);assert.match(source,/BEGIN ISOLATION LEVEL REPEATABLE READ READ ONLY/);});
test("read repository API has no semantic verification or read-selection shortcut",()=>{const api=require("../dist/services/rcv017PostgresReadRepository");assert.deepEqual(Object.keys(api).sort(),["Rcv017PostgresAnalysisReadRepository","Rcv017ReadRepositoryError"]);assert.deepEqual(Object.getOwnPropertyNames(Rcv017PostgresAnalysisReadRepository.prototype).sort(),["constructor","loadAnalysisById"]);});
